export const productProfile = {
  repo: 'm5stack-codex-pet-notifier',
  version: '0.2.0-beta.1',
  tag: 'v0.2.0-beta.1',
  domain: 'IoT',
  ideaNo: 18,
  platformType: 'iot-simulator-mock',
  defaultPairingCode: '123456',
  sampleDeviceId: 'm5stack-sample-001',
  requiredRuntimeSignals: [
    'simulator',
    'mockDevice',
    'sampleTelemetry',
    'deviceAdapter',
    'hostAdapter',
    'lanHostBridge',
    'dashboardGui',
    'codexRelay',
    'codexSessionAutoRelay',
    'codexAppServerAdapter',
    'longRunBridge',
    'installerSigningPrepared',
    'securityPrivacy'
  ],
  requiredDocs: [
    'README.md',
    'AGENTS.md',
    'SKILL.md',
    'docs/requirements.md',
    'docs/specification.md',
    'docs/design.md',
    'docs/architecture.md',
    'docs/implementation-plan.md',
    'docs/test-plan.md',
    'docs/manual-test.md',
    'docs/manual-test-automation.md',
    'docs/gui-tools-manual-check.md',
    'docs/installation-guide.md',
    'docs/user-guide.md',
    'docs/release-checklist.md',
    'docs/security-privacy-checklist.md',
    'docs/competitive-benchmark.md',
    'docs/evaluation-criteria.md',
    'docs/formal-release-platform.md',
    'docs/traceability-matrix.md',
    'docs/qcds-evaluation.md',
    'docs/qcds-strict-metrics.json',
    'docs/qcds-regression-baseline.json',
    'docs/qcds-remote-benchmark.md',
    'docs/qcds-strict-gap-analysis.md',
    'docs/long-run-operations.md',
    'docs/core2-soak-result.json',
    'docs/signed-installer-plan.md',
    'docs/codex-app-server-api-integration.md',
    'docs/signed-installer-pipeline-result.json',
    'docs/codex-app-server-runtime-probe-result.json',
    'docs/formal-release-automation-result.json',
    'docs/adapter-review.md',
    'docs/source-idea-pack.json',
    'docs/release-evidence.json',
    'docs/strict-manual-test-addendum.md',
    'docs/hardware-runtime-evidence.json',
    'docs/host-bridge-manual-check.md',
    'docs/codex-relay-manual-check.md',
    'docs/m5stack-choice-workflow.md',
    'docs/releases/v0.2.0-beta.1.md'
  ]
};
