export const productProfile = {
  repo: 'm5stack-codex-pet-notifier',
  version: '0.1.0-alpha.1',
  tag: 'v0.1.0-alpha.1',
  domain: 'IoT',
  ideaNo: 18,
  platformType: 'iot-simulator-mock',
  defaultPairingCode: '123456',
  sampleDeviceId: 'm5stack-sample-001',
  requiredRuntimeSignals: [
    'simulator',
    'mockDevice',
    'sampleTelemetry',
    'deviceAdapter',
    'hostAdapter',
    'securityPrivacy'
  ],
  requiredDocs: [
    'README.md',
    'AGENTS.md',
    'SKILL.md',
    'docs/requirements.md',
    'docs/specification.md',
    'docs/design.md',
    'docs/architecture.md',
    'docs/implementation-plan.md',
    'docs/test-plan.md',
    'docs/manual-test.md',
    'docs/installation-guide.md',
    'docs/user-guide.md',
    'docs/release-checklist.md',
    'docs/security-privacy-checklist.md',
    'docs/competitive-benchmark.md',
    'docs/evaluation-criteria.md',
    'docs/traceability-matrix.md',
    'docs/qcds-evaluation.md',
    'docs/qcds-strict-metrics.json',
    'docs/qcds-regression-baseline.json',
    'docs/qcds-remote-benchmark.md',
    'docs/qcds-strict-gap-analysis.md',
    'docs/source-idea-pack.json',
    'docs/release-evidence.json',
    'docs/strict-manual-test-addendum.md',
    'docs/releases/v0.1.0-alpha.1.md'
  ]
};
